# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            #anonymous: ~            
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
     #   - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
     #   - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
     #   - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }
        
        
    #    harsh:
    #        algorithm: bcrypt
    #        cost: 15
    #encoders:
    #    one:
    #        algorithm: null
    #    Symfony\Component\Security\Core\User\User: plaintext

    #providers:
    #    our_db_provider:
    #        entity:
    #            class: AppBundle\Entity\User
    #            property: email
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    #providers:
    #    in_memory:
    #        memory: ~
            #    users:
            #       admin:
            #           password: 111
            #            roles: 'ROLE_ADMIN'
            #        user:
            #            password: 111
            #            roles: 'ROLE_USER'
    #firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        #dev:
        #    pattern: ^/(_(profiler|wdt)|css|images|js)/
        #    security: false

        #main:
        #    anonymous: ~

            #pattern:    ^/
            #http_basic: ~
            #provider: our_db_provider

            #guard:
            #    authenticators:
            #        - app.security.login_form_authenticator

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
     #       http_basic: ~
            #    failure_path: homepage
            # https://symfony.com/doc/current/security/form_login_setup.html

            #form_login:
            #    failure_path: homepage

            #    login_path: security_login
            #    check_path: security_login

    #        logout:
    #            path: ^/logout

            #guard:
            #    authenticators:

            #        - app.security.login_form_authenticator
    #access_control:
        # require ROLE_ADMIN for /admin*
    #    - { path: ^/admin, roles: ROLE_ADMIN }
    #    - { path: ^/jspage, roles: ROLE_USER }